#Sample Dockerfile for NodeJS Apps

FROM node:22

ENV NODE_ENV=production

WORKDIR /src

COPY ["package.json", "pnpm-lock.yaml*", "./"]

RUN pnpm install --production

COPY . .

EXPOSE 8080

CMD [ "pnpm", "start" ]