const EXIT_SUCCESS = 0;
const EXIT_INVALID_ARGUMENT = 1;
const MENU_EXIT = "X";
const MENU_HELP = "?";
const HMAC_ALGORITHM = "sha3-256";

module.exports = {
  EXIT_SUCCESS,
  EXIT_INVALID_ARGUMENT,
  MENU_EXIT,
  MENU_HELP,
  HMAC_ALGORITHM,
};
